name: pomodore
description: A new Flutter project.

publish_to: "none"

version: 1.3.0+6

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # theming
  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.5
  google_fonts: ^6.2.1
  ionicons: ^0.2.1
  flutter_spinkit: ^5.1.0
  flex_color_scheme: ^8.1.1
  flutter_launcher_icons: ^0.14.3
  rive: ^0.13.20

  # state management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  flutter_hooks: ^0.20.5

  # dependency injection
  get_it: ^8.0.3

  # database and storage
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_secure_storage: ^9.2.4
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  drift: ^2.25.1
  sqlite3_flutter_libs: ^0.5.30

  # generators
  uuid: ^4.5.1

  # calenders
  calendar_timeline: ^1.0.5
  timeline_tile: ^2.0.0
  date_time_line: ^0.0.3

  # charts
  flutter_heatmap_calendar: ^1.0.5
  syncfusion_flutter_charts: ^28.2.6
  fl_chart: ^0.70.2

  # utility
  intl: ^0.19.0
  #  flutter_datetime_picker: ^1.5.1
  dartz: ^0.10.1
  awesome_notifications: ^0.10.0

  # sensors
  vibration: ^3.1.3
  audioplayers: ^6.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  pinput: ^5.0.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  drift_dev: ^2.25.2
  test: ^1.16.0
  flutter_lints: ^3.0.2
  build_runner: ^2.4.15
  bloc_test: ^10.0.0
  mockito: ^5.3.2
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - .env

  fonts:
    - family: sspro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
    - family: inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
